### ISSUE TITLE
一直提示执行 `flutter pub get` 

### ISSUE THREAD

**Issue by wittyneko** [nEdAy/Flutter-Toolkit#1]
```
/Library/flutter_2.10.0-stable/bin/flutter packages pub run build_runner watch
The pubspec.yaml file has changed since the pubspec.lock file was generated, please run "flutter pub get" again.
pub finished with exit code 65
build_runner Error! Exit with code: 65
```
已经执行 `flutter pub get` 了还说一直报错

**Comment by nEdAy** [comment]
`watch` 不是很可靠，他没有携带 `--delete-conflicting-outputs`，后续我会考虑加上这个参数
如果您确保 `flutter pub get` 可以尝试 先点击执行 `clean` 然后再点击执行 `build`（或 点击执行 `rebuild`, `rebuild` 是  `build` 携带 `--delete-conflicting-outputs`）
