### ISSUE TITLE
[FEATURE_REQUEST] Add Support for partial builds

### ISSUE THREAD

**Issue by luis901101** [nEdAy/Flutter-Toolkit#14]
It would be great if there were an option to `run build_runner build --build-filter path/to/file.g.dart`
The idea is to be able to generate build for just one file, like when you have a big project and you only add a property to one entity. So when the user `Control+Enter` inside a class the plugin context menu shows up with the option to run build runner for this file, then the plugin should check if the file contains an entry like: `part 'chat_user.g.dart';` then take the class path and pass it to the `--build-filter` using the extension defined in the `part` as it could be different builders like freeze, chopper_generator, json_serializable, etc.

Docs here: https://github.com/dart-lang/build/blob/master/docs/partial_builds.md

**Comment by myxzlpltk** [comment]
I already pull request here https://github.com/nEdAy/Flutter-Toolkit/pull/17

**Comment by nEdAy** [comment]
> I already pull request here #17

Thanks @myxzlpltk 
New release version v2.4.6 has been published.

**Comment by luis901101** [comment]
Thanks @myxzlpltk I was able to run partial builds from the context menu on the file.dart from project explorer, although it would be great to have the same **"Run Partial Build Runner"** option in the `Control+Enter` menu
