### ISSUE TITLE
support: Add support of Hedgehog 2023.1.1

### ISSUE THREAD

**Issue by dhruvanbhalara** [nEdAy/Flutter-Toolkit#15]
- Android Studio Hedgehog | 2023.1.1 is now available in the Stable channel.

**Comment by M-Ahal** [comment]
+1

**Comment by aldee** [comment]
I've created the PR here: #16

**Comment by aldee** [comment]
If you can't wait for the PR to be merged, you can always checkout my fork on your local machine, and run ./gradlew buildPlugin

and install the .zip file generated in folder build/dependencies in your IntelliJ IDE
