### ISSUE TITLE
After upgrading to 2021.1.1 patch3, the tool bar icons disappeared

### ISSUE THREAD

**Issue by ash0080** [nEdAy/Flutter-Toolkit#2]
Android Studio Bumblebee | 2021.1.1 Patch 3
Build #AI-211.7628.21.2111.8309675, built on March 17, 2022
Runtime version: 11.0.11+9-b1341.60 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3.1

After upgrading to patch3, the tool bar icons disappeared, and reinstallation didn't help, but right-click on `Customize Menus and Toolbars`, it shows that it exists

**Comment by nEdAy** [comment]
![image](https://user-images.githubusercontent.com/10076735/163085289-5e9a88f6-d7b5-4c6b-a837-3f1783622001.png)

The latest stable version (patch 3) I've been using, and the toolbar on my side shows fine.

Display is controlled by [ProjectChecker](https://github.com/nEdAy/Flutter-Toolkit/blob/2a589dd22b9e6ce78f6c907c57f9be6f37810cfa/src/main/kotlin/cn/neday/excavator/checker/ProjectChecker.kt)
Please check whether the project you have opened contains the following file or folder:
`"lib", ".metadata", ".packages", "pubspec.lock", "pubspec.yaml"`

**Comment by ash0080** [comment]
![Screen Shot 2022-04-13 at 23 36 19](https://user-images.githubusercontent.com/2803210/163217382-1b5a2a1b-3e56-4d9e-b5f7-7defeb8c2bd9.png)
![Screen Shot 2022-04-13 at 23 36 05](https://user-images.githubusercontent.com/2803210/163217404-9adc3005-9470-486b-a52e-b92878fadaff.png)

Everything was fine 2 days ago

**Comment by ash0080** [comment]
@nEdAy It's done, I changed the name of the project folder, then it works fine, is it not supported to have spaces in the folder?

**Comment by nEdAy** [comment]
![image](https://user-images.githubusercontent.com/10076735/163294358-45b9cb74-3596-46b3-b355-06784c6c1289.png)
Project name or project folder name containing spaces I test can be displayed normally; 
As I mentioned above, the project must have the necessary files and folders: "lib", ".metadata", ".packages", "pubspec.lock", "pubspec.yaml"

**Comment by ash0080** [comment]
> ![image](https://user-images.githubusercontent.com/10076735/163294358-45b9cb74-3596-46b3-b355-06784c6c1289.png) Project name or project folder name containing spaces I test can be displayed normally; As I mentioned above, the project must have the necessary files and folders: "lib", ".metadata", ".packages", "pubspec.lock", "pubspec.yaml"

I'm sure that the files and folders you mentioned are not missing, I just changed the folder name, then it works. Then I don't know what the problem is, because there is no error reported, it just disappears.

**Comment by nEdAy** [comment]
Ok, I will pay attention to this situation and close this issue. 
If the problem occurs again, you can reopen it.
Thanks for use and feedback.
