### ISSUE TITLE
Icons disappears on new Intellj interface

### ISSUE THREAD

**Issue by lucasdidur** [nEdAy/Flutter-Toolkit#8]
When using the new Intellj interface, the icons disappears.

**Comment by nEdAy** [comment]
That's a real problem. `ToolbarRunGroup` appears to be unavailable.
But I don't know how to adapt to the New UI.

The right mouse-click `EditMenu` still works.
![image](https://user-images.githubusercontent.com/10076735/215310591-dd7e7321-d4e8-41b9-bdd5-17154b7bceb5.png)

**Comment by nEdAy** [comment]
#10
